- numpy
- pandas
- matplotlib

# numpy

#### python中的数组类型（一般不直接用，numpy中会使用到）

In [2]:
import array
a=array.array('i',range(10))
type(a)

array.array

In [3]:
import numpy as np

#### 从列表转换数组(numpy中的数组)

In [4]:
lstA=list(range(10))
b=np.array(lstA)
type(b)

numpy.ndarray

#### 生成numpy数组

In [5]:
#一维0数组
a=np.zeros(10,dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
#二维任意数组
c=np.full((3,3),3.14)
c

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [7]:
#比照已有数组尺寸，新建数组
np.full_like(c,4.12)

array([[4.12, 4.12, 4.12],
       [4.12, 4.12, 4.12],
       [4.12, 4.12, 4.12]])

#### 随机数random

In [8]:
import random
#随机整形
random.randint(5,10)

10

#### numpy中的随机数

In [9]:
#普通随机数
np.random.randint(0,9)

2

In [10]:
#随机整形数组
np.random.randint(0,9,(3,3))

array([[5, 6, 8],
       [2, 2, 0],
       [1, 3, 4]])

In [11]:
#随机浮点数组
np.random.random((3,3))

array([[0.08718834, 0.79037149, 0.18754397],
       [0.80397737, 0.75733857, 0.30786783],
       [0.45626411, 0.87134894, 0.62822193]])

In [12]:
#随机均值为0，标准差为1的正态分布数组
np.random.normal(0,1,(3,3))

array([[ 1.17474311,  0.59936999,  1.58043647],
       [-0.02509234,  0.22262758,  0.55877531],
       [-0.14604336, -0.46220365, -1.58026019]])

In [13]:
#生成数组范围0-10，步长2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
#生成0-20之间的元素为101个的线性序列
np.linspace(0,20,101)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8, 20. ])

In [15]:
#生成4阶单位矩阵
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 二维数组访问

In [16]:
#新建一个列表
var=[[1,2,3],[4,5,6],[7,8,9]]
#访问二维列表中的元素只能通过两个中括号[][]完成
var[1][2]

6

In [17]:
#列表转化为二维数组
a=np.array(var)
#访问二维数组可以使用[][]或[,]完成，推荐使用[,]便于切片操作
a[1][2],a[1,2]

(6, 6)

In [18]:
#数组切片,取前两行的前1列
a[:2,:1]

array([[1],
       [4]])

In [19]:
#数组维度
a.ndim

2

In [20]:
#数组形状（尺寸）
a.shape

(3, 3)

In [21]:
#数组大小（总元素个数）
a.size

9

In [22]:
#元素数据类型
a.dtype

dtype('int32')

In [23]:
#元素大小（字节）
a.itemsize

4

In [24]:
#数组大小（占用空间）
a.nbytes

36

### 数值运算

In [25]:
print(a)
print(a+10)
print(a*10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


|操作符|numpy函数|功能|
|-|-|-|
|+|add|Addition (e.g.,1+1=2)|
|-|subtract|Subtraction (e.g.,3-2=1)|
|-|negative|Unary negation (e.g.,-2)|
|\*|multiply|Multiplication (e.g.,3\*2=6)|
|/|divide|Division (e.g.,3/2=1.5)|
|//|floor_divide|Floor Division (e.g.,3//2=1)|
|\*\*|power|Exponentiation (e.g.,3\*\*2=9)|
|%|mod|Modulus/remainder (e.g.,9%4=1)|

### 统计运算

In [54]:
#python内置求和
print(sum([1,2,3,4]))
print(a)
print(sum(a))#对列进行求和

10
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]


In [53]:
#numpyq求和
print(a)
print(np.sum(a))
print(np.sum(a,axis=0))#对某个维度进行求和
print(np.sum(a,axis=1))#对某个维度进行求和

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]


### Notebook执行效率分析
%timeit

In [55]:
n=np.random.rand(10000)
%timeit sum(n)#ms级运算时间，慢

1.7 ms ± 30.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [56]:
%timeit np.sum(n)#微秒级运算时间，快

7.15 µs ± 154 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 比较运算

In [58]:
a>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [60]:
a<3

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [61]:
a==3

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [62]:
np.all(a>3)#是否全为true

False

In [64]:
np.any(a>3)#是否有true

True

### 变形

In [87]:
n=np.random.randint(0,100,(4,6))
n

array([[29,  7, 74, 73, 51, 75],
       [15, 73, 47, 72, 53, 64],
       [ 4, 57, 77, 69, 61, 86],
       [ 4, 50, 62, 38, 66,  6]])

In [88]:
n.reshape(3,8)

array([[29,  7, 74, 73, 51, 75, 15, 73],
       [47, 72, 53, 64,  4, 57, 77, 69],
       [61, 86,  4, 50, 62, 38, 66,  6]])

### 排序

In [90]:
s=n.copy()
s.sort(axis=0)#注意！这个操作直接在原矩阵上进行
s

array([[ 4,  7, 47, 38, 51,  6],
       [ 4, 50, 62, 69, 53, 64],
       [15, 57, 74, 72, 61, 75],
       [29, 73, 77, 73, 66, 86]])

#### 升序

In [91]:
s=n.copy()
s.sort(axis=1)#注意！这个操作直接在原矩阵上进行
s

array([[ 7, 29, 51, 73, 74, 75],
       [15, 47, 53, 64, 72, 73],
       [ 4, 57, 61, 69, 77, 86],
       [ 4,  6, 38, 50, 62, 66]])

In [94]:
s=n.copy()
s.sort()#默认axis=1
s

array([[ 7, 29, 51, 73, 74, 75],
       [15, 47, 53, 64, 72, 73],
       [ 4, 57, 61, 69, 77, 86],
       [ 4,  6, 38, 50, 62, 66]])

### 拼接

In [97]:
a=np.array([1,2,3])
b=np.array([[0,2,4],[1,3,5]])

In [101]:
#拼接时所有参数必须相同尺寸
np.concatenate([b,b])

array([[0, 2, 4],
       [1, 3, 5],
       [0, 2, 4],
       [1, 3, 5]])

In [102]:
np.concatenate([a,a])

array([1, 2, 3, 1, 2, 3])

In [105]:
np.concatenate([b,b],axis=1)#从第二个维度拼接

array([[0, 2, 4, 0, 2, 4],
       [1, 3, 5, 1, 3, 5]])

In [4]:
import numpy as np
xxi=np.zeros((4,5,3),np.uint8)
for i in range(0,len(xxi)):
    for j in range(0,len(xxi[i])):
        for k in range(0,len(xxi[i,j])):
            print(xxi[i,j,k])
            print('xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]')
        


0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0
xxi[ixxxxxxxxxxxxxxxxxxxxxxxxxxxx]
0